### PR TITLE
Extract stacktraces from errors of the pkg/errors package

### LINKED ISSUE #37: Extract stacktraces from errors of pkg/errors
Thanks for making this great library.

I am transitioning some code to use  [pkg/errors](https://github.com/pkg/errors) for error logging. This package captures the stacktraces of the place where the errors are created. Those stacktraces are more precise than the ones collected by gobrake, since the error creation and its logging can be far away (I use sirupsen/logrus's log.Errorln(err)).

Before I send a PR I'd like to ask your opinion about this feature. Would you merge a PR that implements it? I've one ready.

### PR DESCRIPTION
**Pull request by ihrwein**
TODO:
* [x] write test
* [x] change `%s` to `%+s` (to use relative paths)

Errors created by pkg/errors capture the stacktrace of the place when
the errors are created. It makes debugging much more easier if
developers can see the real origin of the errors.

This commit introduces the special handling of errors from the
pkg/errors package.

Fixes #37 

Signed-off-by: Tibor Benke <ihrwein@gmail.com>

### CODE REVIEW

File: notice.go [hunk 1]
```diff
@@ -63,17 +66,84 @@ func (n *Notice) String() string {
...
+		return nil
+	}
+
+	fn := strings.TrimSpace(parts[0])
+	file := strings.TrimSpace(parts[1])
+	line, err := strconv.ParseInt(parts[2], 10, 64)
+	if err != nil {
+		return nil
+	}
+	return &StackFrame{file, int(line), fn}
```
Comment (vmihailenco) [inline notice.go]: I did not try, but what about something like:

```
return &StackFrame{
    File: fmt.Sprintf("%s", f)
    Line: fmt.Sprintf("%d", f)
    Func: fmt.Sprintf("%n", f),
}
```

Probably it is not worth it to create separate function

File: notice.go [hunk 2]
```diff
@@ -63,17 +66,84 @@ func (n *Notice) String() string {
...
+func stackFromErrorWithStackTrace(e stackTracer) []StackFrame {
+	var frames []StackFrame
+	for _, f := range e.StackTrace() {
+		pf := parseFrame(&f)
+		if pf != nil {
+			frames = append(frames, *pf)
+		}
+	}
+	// Remove the frames of runtime.main and runtime.goexit
+	frames = frames[:len(frames)-2]
```
Comment (vmihailenco) [inline notice.go]: Let's omit this at least for now? First we didn't remove these frames until now and second Go for some reason decided to show them...

**Comment by vmihailenco** [comment]
Looks nice! Can you please move all stack related code to `util.go` (probably also renaming it to `stack.go`)? Also having at least one test would be nice.

**Comment by vmihailenco** [comment]
Thanks. I will merge and make few edits.

**Comment by ihrwein** [comment]
Thanks!

**Comment by vmihailenco** [comment]
Release v3.2.0. Thanks again for your contribution.

**Comment by ihrwein** [comment]
You're welcome.
